---
- name: Check if asdf {{ asdf_version}} already installed
  stat:
    path: /opt/asdf-{{ asdf_version }}
  register: asdf_directory
  tags: asdf
- name: Download asdf {{ asdf_version }}
  get_url:
    url: "https://github.com/asdf-vm/asdf/archive/v{{ asdf_version}}.tar.gz"
    checksum: "sha256:{{ asdf_sha256 }}"
    dest: "/tmp/asdf-{{ asdf_version }}.tar.gz"
  tags: asdf
  when: not asdf_directory.stat.exists
- name: Create asdf-{{ asdf_version }} directory
  file:
    path: "/opt/asdf-{{ asdf_version }}"
    state: directory
    mode: 0755
  tags: asdf
- name: Install asdf {{ asdf_version }}
  unarchive:
    src: "/tmp/asdf-{{ asdf_version }}.tar.gz"
    extra_opts:
      - "--strip-components=1"
    dest: "/opt/asdf-{{ asdf_version }}"
    remote_src: yes
  tags: asdf
  when: not asdf_directory.stat.exists
- name: Symlink default asdf
  file:
    src: "asdf-{{ asdf_version }}"
    dest: "/opt/asdf"
    state: link
  tags: asdf
- name: Install asdf to the path
  lineinfile:
    path: /etc/bash.bashrc
    regexp: '^\.\s+.*asdf\.sh'
    line: ". /opt/asdf/asdf.sh"
  tags: asdf
